version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka_container
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  bokeh-server:
    build: .
    container_name: bokeh_container
    ports:
      - "5006:5006"
    depends_on:
      - kafka

volumes:
  kafka_data:
    driver: local
